# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY.
_commit: v1.2.1
_src_path: gh:acidsailor/go-scaffolds
author: Denis Shaporov / acidsailor
author_email: d@shaporov.dev
go_version: '1.26'
module_path: github.com/acidsailor/tinvest
project_name: tinvest
project_type: library

